
project_id = "nyadgiutmweuyxqetfuh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[edge_runtime]
enabled = true
port = 54326

[functions.create-checkout]
verify_jwt = false

[functions.handle-payment-success]
verify_jwt = false

[functions.send-mfa-email]
verify_jwt = false

[analytics]
enabled = false
port = 54327

[functions]
verify_jwt = true
